# Generated by Django 3.2.13 on 2022-05-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=30)),
                ('topic', models.CharField(max_length=30)),
                ('date', models.DateField()),
            ],
        ),
    ]
